config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :serie, only: [:index, :movies]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/serie_controller.rb
class SerieController < ApplicationController
    def index
        
    end
    def movies
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/serie_helper.rb
module SerieHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bigbangtheory</title>
    <meta charset="utf-8" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/serie/index.html.erb
<header>
  <div class="navbar navbar-dark bg-dark">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand"></a>
    </div>
  </div>
</header>

<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">The Big Bang Theory</h1>
      <p class="lead text-muted" style="color: white;">"Bazinga!"</p>
    </div>
  </section>

  <div class="album text-muted">
    <div class="container">
      <div class="row" id="moviecards">
        
      </div>
    </div>
  </div>

</main>

<footer class="text-muted">
  <div class="container">
    <p>Merve Yilmaz</p>
  </div>
</footer>

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script type="text/javascript">
  $(document).ready(function(){  
    $.ajax({
      url: "https://omdbapi.com/?s=Big+Bang+Theory&apikey=852159f0",
      dataType: "json"
    }).done(function(result) {
      var sorted = $(result["Search"]).sort(function(a, b) {
      if(($(a)[0].Type == 'movie')&($(b)[0].Type == 'movie')){
        var a = $(a)[0].Year, b = $(b)[0].Year;
        return a.localeCompare(b, undefined, {numeric: true})
      }
      })
      $(sorted).each(function(){
        var urlforposter = $(this)[0].Poster
        if(urlforposter == "N/A"){
          urlforposter = "https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg"
        }
        $("#moviecards").append("<div class='card' id='serie'><img src='"+ urlforposter + "' alt='Card image cap'><h3 id='serietitle'>" + $(this)[0].Title + "</h3><p class='card-text'>Type: "+ $(this)[0].Type + "</p><p class='card-text'>Year: "+ $(this)[0].Year + "</p><p class='card-text'>ImdbID: "+ $(this)[0].imdbID + "</p></div>")
      });
    });
  });
</script>

app/views/serie/movies.html.erb
<%= button_to "Hier klicken" , serie_path(), method: :get, :onclick => "myFunction()" %>
<script>
  function myFunction(){
  alert("Oh man :(");
  }
</script>